handlers = java.util.logging.ConsoleHandler
.level = INFO
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

niva.vannmiljo.level = ALL
org.geotools.data.arcgisrest.level = ALL
