idAuthProvider = niva.aquamonitorAuthenticationProviderPanelInfo
shortAuthProviderPanel = Aquamonitor
titleAuthProviderPanel = Aquamonitor autentisering
descriptionAuthProviderPanel = Bruker tjeneste i Aquamonitor til å håndtere pålogging.

niva.geoserver.security.AquamonitorAuthenticationProvider.title = Aquamonitor autentisering ved API
