handlers = java.util.logging.ConsoleHandler
.level = INFO
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

niva.geotools.level = FINE
niva.aquamonitor.level = INFO
org.geotools.data.postgis.level = ALL
org.geotools.data.wfs.level = ALL
org.geotools.http.level = ALL

