handlers = java.util.logging.ConsoleHandler
.level = FINE
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
it.geosolutions.level = WARNING
org.geotools.data.postgis.level = WARNING
org.geotools.jdbc.level = WARNING
org.geoserver.config.level = WARNING
org.geoserver.catalog.level = WARNING
com.sun.level = WARNING
