handlers = java.util.logging.ConsoleHandler

.level = FINE
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

org.geotools.data.postgis.level = INFO
org.geotools.jdbc.level = INFO

org.geoserver.config.level = INFO
org.geoserver.catalog.level = INFO
sun.level = INFO
it.geosolutions.imageio.plogins.arcgrid.spi.level=WARNING
it.geosolutions.imageio.plogins.arcgrid.raster.level=WARNING
jdk.level = INFO
com.sun.level = INFO
org.geotools.util.level = INFO